/*
MEMBER_ID   : 회원 ID
MEMBER_NAME : 회원 이름
TLNO        : 연락처
GENDER      : 성별
DATE_OF_BIRTH : 생년월일

*/

-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, DATE_OF_BIRTH
FROM MEMBER_PROFILE
WHERE 
GENDER = 'W' 
    AND MONTH(DATE_OF_BIRTH) = 3 
    AND TLNO IS NOT NULL
ORDER BY MEMBER_ID;