-- 코드를 입력하세요
-- FIRST_HALF의 기본키는 FLAVOR
-- ICECREAM_INFO의 기본키는 FLAVOR

SELECT F.FLAVOR
FROM FIRST_HALF F
JOIN ICECREAM_INFO I ON F.FLAVOR = I.FLAVOR
WHERE F.TOTAL_ORDER > 3000 
AND I.INGREDIENT_TYPE = 'fruit_based'
ORDER BY TOTAL_ORDER DESC;